name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install prophet arch matplotlib pandas requests

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Verify Go installation
      run: go version

    - name: Install Go dependencies
      run: go mod tidy

    - name: Run tests and generate coverage report
      run: go test -coverprofile=coverage.out -v ./...

    - name: Upload coverage reports to Codecov2
      uses: codecov/codecov-action@v4.0.1
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
